import { readFileSync } from "node:fs";
import { z } from "zod";

/** One deployable process inside the stack artifact (see scripts/pack-stack.sh,
 *  which writes the manifest). */
export const stackComponentSchema = z.object({
  name: z.string().min(1),
  /** Runtime that hosts the entry. "bun" is what the artifact ships. */
  runtime: z.enum(["bun", "node"]),
  /** Directory the entry runs from, relative to the artifact root. */
  cwd: z.string().min(1),
  /** Entry file, relative to cwd. */
  entry: z.string().min(1),
  port: z.number().int().positive().optional(),
  healthUrl: z.string().min(1).optional(),
  /** Env for the child; values may carry {root}/{dataDir}/{omaBin}/{secret:NAME}. */
  env: z.record(z.string(), z.string()).default({}),
  /** Secret names the launcher must generate and inject into this component's
   *  env (same effect as referencing {secret:NAME} in env, for a component
   *  that needs the value under its own name). */
  secrets: z.array(z.string()).default([]),
  dependsOn: z.array(z.string()).default([]),
});
export type StackComponent = z.infer<typeof stackComponentSchema>;

export const stackManifestSchema = z.object({
  schemaVersion: z.literal(1),
  name: z.string().min(1),
  version: z.string().min(1),
  components: z.array(stackComponentSchema).min(1),
});
export type StackManifest = z.infer<typeof stackManifestSchema>;

export class StackManifestError extends Error {}

export function parseStackManifest(raw: unknown): StackManifest {
  const parsed = stackManifestSchema.safeParse(raw);
  if (!parsed.success) {
    throw new StackManifestError(
      `invalid stack manifest: ${parsed.error.issues[0]?.message ?? "?"}`,
    );
  }
  return parsed.data;
}

export function readStackManifest(path: string): StackManifest {
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(path, "utf8"));
  } catch (err: unknown) {
    throw new StackManifestError(
      `cannot read ${path}: ${err instanceof Error ? err.message : err}`,
    );
  }
  return parseStackManifest(raw);
}

export interface PlaceholderContext {
  /** Artifact root (the unpacked version directory). */
  root: string;
  /** Persistent data root, shared across versions so upgrades keep state. */
  dataDir: string;
  /** Executable the backend spawns per Run — oma itself. */
  omaBin: string;
  secrets: Record<string, string>;
}

/** Resolve the manifest's placeholders. Unknown ones throw: a silent empty
 *  string would start a component with a broken path or secret. */
export function resolvePlaceholders(value: string, ctx: PlaceholderContext): string {
  return value.replace(/\{([^}]+)\}/g, (_match, token: string) => {
    if (token === "root") return ctx.root;
    if (token === "dataDir") return ctx.dataDir;
    if (token === "omaBin") return ctx.omaBin;
    if (token.startsWith("secret:")) {
      const name = token.slice("secret:".length);
      const secret = ctx.secrets[name];
      if (secret === undefined) throw new StackManifestError(`manifest wants secret ${name}`);
      return secret;
    }
    throw new StackManifestError(`unknown placeholder {${token}}`);
  });
}

export function resolveComponentEnv(
  component: StackComponent,
  ctx: PlaceholderContext,
): Record<string, string> {
  const env: Record<string, string> = {};
  // A declared secret is generated by the launcher and injected under its own
  // name — the manifest says "this component needs it" once. An explicit env
  // entry for the same key wins.
  for (const name of component.secrets) {
    const secret = ctx.secrets[name];
    if (secret === undefined) {
      throw new StackManifestError(`component ${component.name} declares secret ${name}`);
    }
    env[name] = secret;
  }
  for (const [key, value] of Object.entries(component.env)) {
    env[key] = resolvePlaceholders(value, ctx);
  }
  return env;
}

export function componentDir(component: StackComponent, root: string): string {
  return `${root}/${component.cwd}`.replace(/\/+/g, "/");
}

/** Components in startup order: dependencies first, declaration order between
 *  independents (a topological sort would be overkill for a 2-process stack,
 *  but an explicit dependsOn must not be ignored). */
export function startupOrder(manifest: StackManifest): StackComponent[] {
  const ordered: StackComponent[] = [];
  const remaining = [...manifest.components];
  while (remaining.length > 0) {
    const ready = remaining.filter((c) =>
      c.dependsOn.every((dep) => ordered.some((o) => o.name === dep)),
    );
    if (ready.length === 0) {
      throw new StackManifestError(
        `circular dependsOn among: ${remaining.map((c) => c.name).join(", ")}`,
      );
    }
    for (const c of ready) {
      ordered.push(c);
      remaining.splice(remaining.indexOf(c), 1);
    }
  }
  return ordered;
}
