import type { Message } from "@chengchenccc/message";
import type { BackendModelRef } from "./model.js";

/** A projected history entry. `productEntryId` is the stable Agent Context
 *  entry identity, retained so the Runtime can write it onto its appended
 *  entries and never persist the same canonical Message twice. It is not a
 *  Runtime message ID and must not be regenerated by the Runtime. */
export interface ProjectedHistoryItem {
  readonly productEntryId: string;
  readonly message: Message;
}

/** Runtime-accessible workspace and its permission boundary. */
export interface WorkspaceBinding {
  readonly root: string;
  readonly access: "read_only" | "read_write";
}

/** Frozen per-Run configuration. Fixed at Agent Run start; every `execute()`
 *  carries it so model and system prompt changes take effect on the next Run
 *  without any shared state. Product Tool definitions ride the workspace
 *  files (.oma/product-tools.json, ADR 0003 decision 6), not this snapshot.
 *  Parameterized by `K` so the model ref's backendKind is locked to the
 *  Backend's kind. */
export interface AgentRunSnapshot<K extends string = string> {
  readonly runId: string;
  readonly model: BackendModelRef<K>;
  readonly systemPrompt?: string;
  /** Skill pack roots (absolute dirs scanned for SKILL.md), frozen at Run
   *  creation. The Runtime loads them via the progressive skill plugin. */
  readonly skillRoots?: readonly string[];
  /** The branch's CLI session reference (ADR 0003 decision 6): an opaque
   *  pointer the oma resolves itself (its own native session
   *  storage). Absent = fresh session. The product stores only this
   *  reference — never manages the CLI's session files. */
  readonly cliSessionRef?: string;
  /** Frozen permission_mode (ask/auto/deny/yolo), mapped per backend at
   *  dispatch (ADR 0020 decision 7). "yolo" = ungated run. */
  readonly permissionMode?: "ask" | "auto" | "deny" | "yolo";
  /** Optional workflow budget (tokens) frozen at Run creation. */
  readonly workflowBudgetTokens?: number;
  readonly configRevision: number;
}
